name: 'Gogamic CI CLI'
author: GOGAMIC <opensource@gogamic.com>

description: 'An CLI/Docker Image used to deploy apps to dokku'
inputs:
  ssh_key:
    required: true
    description: A SSH Private key which is to be encoded in base64
  server_ip:
    required: true
    description: The Instance we you need to deploy the application
  image_url:
    required: true
    description: The full url to the image registry
  name:
    required: true
    description: The Name of the application in the Instance
  
  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - deploy      
    - "-b true"
    - "-s ${{ inputs.ssh_key }}"
    - "-i ${{ inputs.server_ip }}"
    - "-n ${{ inputs.name }}"
    - "-r ${{ inputs.image_url }}"