steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/gogamicc/gogamic-ci-cli", "."]
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gogamicc/gogamic-ci-cli']

images:
  - gcr.io/gogamicc/gogamic-ci-cli